---
- name: Playbook for Dagobah, the yoda Pi.

  hosts: pi-dagobah

  become: no

  roles:
  - { role: disable-swap, become: yes, tags: ["disable-swap"] }
  - { role: pipenv,       become: no,  tags: ["pipenv"] }
